name: Doctolib Scraper & Heartbeat

on:
  workflow_dispatch:
  schedule:
    # Exécution toutes les 15 minutes pour attraper l'heure pile de Paris
    - cron: '*/15 * * * *'

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v4

      - name: ⬡ Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Installation des dépendances
        run: npm install

      - name: 🎭 Installation des navigateurs Playwright
        run: npx playwright install --with-deps chromium

      - name: 🚀 Lancement du Scraper
        env:
          CRON_EXEC: ${{ github.event_name == 'schedule' }}
        run: npm start
